### ISSUE TITLE
Plz ADD A CLOUD SAVING OPTION

### ISSUE THREAD

**Issue by tvrhossain** [Snipaste/feedback#1673] opened 2020-09-30 06:06 UTC
Almost all the other Screen Cap App has a way to upload the captured picture in cloud and provide us with a link so that we can share. This will be a good feature. (U can use any free image sharing cloud API)

**Comment by kasusa** [comment] 2020-11-04 12:08
that would be a lot of work lol

**Comment by septs** [comment] 2021-02-12 06:39
Duplicate of #60

**Closed by septs** 2021-02-12 06:39 UTC
