### ISSUE TITLE
Screenshot OCR needed!!!

### ISSUE THREAD

**Issue by dw0216** [Snipaste/feedback#2499] opened 2023-02-09 18:23 UTC
### Feature Description

Please add OCR(Optical character recognition) feature as it would be one of the key feature to select a screenshot software.

**Comment by Geeyun-JY3** [comment] 2023-02-09 23:52
Duplicate of #188

**Closed by Geeyun-JY3** 2023-02-09 23:52 UTC
Labels: duplicate

**Comment by dw0216** [comment] 2023-02-09 23:56
Will OCR never be implemented as Snipaste's feature?
Snipaste Pro is one of my favorite software but OCR is one essential function I needed which Snipaste is missing...

**Comment by Geeyun-JY3** [comment] 2023-02-11 00:42
I close your issue just because it is duplicate. 
I do not know if it would be implemented, either
