### ISSUE TITLE
PRO without Microsoft Store

### ISSUE THREAD

**Issue by nataloko** [Snipaste/feedback#2645] opened 2023-06-22 12:23 UTC
### Problem Description

Hi,

I want to buy PRO but I can't use Microsoft Store at work, when can we expect option to purchase PRO via different way?

### Platform

Windows Desktop

### Version

2.8.5

**Comment by septs** [comment] 2023-06-23 15:43
Duplicate of #1162

**Closed by septs** 2023-06-23 15:43 UTC
Labels: question
