### ISSUE TITLE
When will linux version be out?

### ISSUE THREAD

**Issue by Neykuratick** [Snipaste/feedback#2285] opened 2022-07-28 20:39 UTC
### Problem Description

Hey, thank you for truly amazing app. This is a wonderful piece of tech you guys made. I love using snipaste and its absence on linux is actually the only thing holding me back from switching to linux from windows, because of the immense impact snipaste has had on my life quality. Please, i really wish snipaste was ported on linux

Is there anything i can do to speed up this process? Maybe you need some help?

### Platform

Windows Desktop

### Version

2.7.3

**Comment by zhangshengping** [comment] 2022-08-01 01:33
40% when 2016

**Comment by septs** [comment] 2023-03-25 12:30
/

**Comment by septs** [comment] 2023-03-25 12:31
Duplicate of https://github.com/Snipaste/feedback/issues/711

**Closed by septs** 2023-03-25 12:31 UTC
Labels: question
