### ISSUE TITLE
Auto Numbering option

### ISSUE THREAD

**Issue by Tamarael** [Snipaste/feedback#2670] opened 2023-07-25 09:08 UTC
### Feature Description

I know we can use the "text" option to add numbers to the image, but I used another app that had the option to simply click and add the numbers automatically with the option to keep the sequence or reset it. I think this would be a great addition to the app.

The benefit of having the "auto numbering" feature is that you only need to click on the image and the number is automatically added and in sequence, we do not need to manually type the numbers in, which reduce the input requirements for the feature to be used.

**Comment by Geeyun-JY3** [comment] 2023-07-25 10:50
This feature needs PRO: https://github.com/Snipaste/feedback/issues/227#issuecomment-628125908

**Comment by Geeyun-JY3** [comment] 2023-07-25 10:51
Duplicate of https://github.com/Snipaste/feedback/issues/227#issuecomment-628125908

**Closed by Geeyun-JY3** 2023-07-25 10:51 UTC
Labels: duplicate
