### ISSUE TITLE
Can't use the pro version on Windows Server 2019

### ISSUE THREAD

**Issue by Jieguohaishihuacai** [Snipaste/feedback#1792] opened 2021-02-03 02:49 UTC
The pro version runs fine on my Windows 10, but only the free version can run on my Windows Server 2019
I can't get the pro version installed on my Windows Server 2019
Is there anyway I can have the pro version work on the Windows Server 2019?
I desperately need the pro version my Server 2019

Thx

软件版本：
运行平台：微软商店 / Windows 桌面 / macOS

**Comment by liulex** [comment] 2021-02-03 16:47
The Pro version relies on Microsoft Store. Maybe you need to install Microsoft Store on your Windows Server.

**Comment by septs** [comment] 2021-02-12 07:11
Duplicate of #1162

**Closed by septs** 2021-02-12 07:11 UTC
