### ISSUE TITLE
When is the first official version of Linux released, is there a plan?

### ISSUE THREAD

**Issue by iamsunxing** [Snipaste/feedback#1042] opened 2018-12-05 00:50 UTC
When is the first official version of Linux released, is there a plan?

**Comment by Riajyuu** [comment] 2018-12-05 03:58
@iamsunxing not in near future

**Comment by ZetaoYang** [comment] 2019-01-02 07:11
@iamsunxing You can try `flameshot`.

**Comment by septs** [comment] 2021-02-12 06:23
Duplicate of #711

**Closed by septs** 2021-02-12 06:23 UTC
