### ISSUE TITLE
Hope to obtain screen XY coordinate value

### ISSUE THREAD

**Issue by Javahhhh** [Snipaste/feedback#2912] opened 2024-04-20 07:35 UTC
### 功能描述

![Uploading Snipaste_2024-04-20_15-34-07.png…]()

**Comment by Geeyun-JY3** [comment] 2024-04-22 08:13
Your pictures was not uploaded successfully.

**Comment by Javahhhh** [comment] 2024-05-07 09:37
![坐标](https://github.com/Snipaste/feedback/assets/112531492/bb810e75-86cc-44c6-bd93-3cf7b912de0b)
obtain screen XY coordinate value ，How did you obtain the code for the x and y coordinates? Can you tell me which line the source code is? thanks

**Comment by Geeyun-JY3** [comment] 2024-05-07 16:04
Duplicate of #2362

**Closed by Geeyun-JY3** 2024-05-07 16:04 UTC
Labels: duplicate
