### ISSUE TITLE
Print Button

### ISSUE THREAD

**Issue by ProxyH** [Snipaste/feedback#324] opened 2017-01-25 17:59 UTC
Hi,

Can you add print button and update print mechanism? Currently when printing large screen loses on the print quality. Image is blurred and not clear.

**Comment by liulex** [comment] 2017-01-27 08:38
The reason of not adding a print button is exactly the poor implementation of the print mechanism. 😅 
The print support will be enhanced in the future, with a print button of course.

**Comment by septs** [comment] 2021-02-12 07:32
Duplicate of #817

**Closed by septs** 2021-02-12 07:32 UTC
Labels: later
