### ISSUE TITLE
Add an option for drop shadows, for windows

### ISSUE THREAD

**Issue by Lunchb0ne** [Snipaste/feedback#2039] opened 2021-11-26 12:33 UTC
It would be really nice if there could be an option for adding drop shadows to screenshots taken of windows, like how it's done on something like MacOS. 

![image](https://user-images.githubusercontent.com/22198661/143581649-a0f4160b-8a91-4673-a296-06b52c841b9e.png)

I feel like that would be a nice feature and really adds to the screenshot. Especially now that Windows 11 forces round corners on windows, maybe this can be used

**Comment by Geeyun-JY3** [comment] 2022-07-08 04:53
Duplicate of #197

**Closed by Geeyun-JY3** 2022-07-08 04:53 UTC
Labels: duplicate
