### ISSUE TITLE
Disabel Magnifier

### ISSUE THREAD

**Issue by lch48a** [Snipaste/feedback#2340] opened 2022-09-18 08:35 UTC
### Feature Description

Hello, would you consider giving the user an option to disable the magnifier? It's a distraction for my workflow, and plus it covers parts of the screen creating unnecessary difficulties in making the right selection. I am on MacOs. Thanks.

**Comment by Geeyun-JY3** [comment] 2022-09-20 00:36
Duplicate of #1207

**Closed by Geeyun-JY3** 2022-09-20 00:36 UTC
Labels: duplicate
