### ISSUE TITLE
新功能需求：截图时增加边框。new feature request, add a border when taking a screenshot

### ISSUE THREAD

**Issue by x-bearcom** [Snipaste/feedback#3157] opened 2024-12-07 14:39 UTC
### 功能描述

Is it possible to add a new feature that allows users to choose whether to add a border when taking a screenshot, and customize the border's color, width, and whether it has a shadow?
能否增加一个新的特性，截图时可选是否增加一个边框，并且可以自定义边框的颜色、宽度、是否有阴影等
The current challenge is that if the screenshot area has a white background and the paste location also has a white background, the screenshot and the paste location will overlap and become indistinguishable from each other.
现在的难题时，截图区域如果是白色背景，粘贴位置也是白色背景，截图和粘贴位置就重叠在一起无法区分开了

**Comment by Geeyun-JY3** [comment] 2024-12-08 10:33
Duplicate of #197

**Closed by Geeyun-JY3** 2024-12-08 10:33 UTC
Labels: duplicate
