### ISSUE TITLE
Hope to add screenshot translation and copy sticker text

### ISSUE THREAD

**Issue by Peng1203** [Snipaste/feedback#2591] opened 2023-04-23 05:59 UTC
### Feature Description

Hope to add screenshot translation and copy sticker text.
Sorry I can't speak English. The above passage is translated by Google.

**Comment by septs** [comment] 2023-04-23 06:28
Duplicate of #188

**Closed by septs** 2023-04-23 06:28 UTC

**Comment by Geeyun-JY3** [comment] 2023-04-23 06:31
Could you please translate [this comment](https://github.com/Snipaste/feedback/issues/2590#issuecomment-1518951155) using Google Translate before opening another _duplicate_ issue?
