### ISSUE TITLE
Open Source OCR Supported?

### ISSUE THREAD

**Issue by kabeep** [Snipaste/feedback#3081] opened 2024-09-28 12:08 UTC
### Feature Description

This feature request may not be strongly related to screenshot/sticking.

### But it is a strong demand for such tools, and ***I'm not the only one***.

I've been using Snipaste since 2020. After taking on more hardcore work.
I had to alternate with other screenshot tools that support pasting and OCR.

I discovered the entrance to the pro version through the ***star emoji*** on the tray menu last week. This is a smart design.

![image](https://github.com/user-attachments/assets/e1a16c44-0663-4ef9-8d71-c785109a72b6)

I use it rarely now, but I would still like to use Snipaste again and pay for it.

---

Based on the dependencies of similar screenshot products. I found _Paddle_ and _Rapid_. 

I tried to develop this repo: [node-paddle-ocr](https://github.com/kabeep/node-paddle-ocr).
The overall experience is that they are *very easy* to transplanted in projects.

Given that your organization is working on multi - platform and multi - language tasks, if this feature request can be adopted, I highly recommend this [RapidOCR](https://github.com/RapidAI/RapidOCR) and [RapidOcrOnnx](https://github.com/RapidAI/RapidOcrOnnx).

Thank you again for your work. It has really helped me.

**Comment by Geeyun-JY3** [comment] 2024-09-28 16:09
Duplicate of #188

**Closed by Geeyun-JY3** 2024-09-28 16:09 UTC
Labels: duplicate
