### ISSUE TITLE
Linux 版多久出来？

### ISSUE THREAD

**Issue by yinxiulong** [Snipaste/feedback#1982] opened 2021-09-24 00:26 UTC
linux 版多久出来？用习惯你这款软件，想用linux 也能用

**Comment by noyidoit** [comment] 2021-10-30 03:42
+1

**Comment by ElvesYuki** [comment] 2021-12-02 07:52
+1

**Comment by dalao-li** [comment] 2022-01-09 11:22
+1

**Comment by FunnyAWM** [comment] 2022-02-25 04:08
+1

**Comment by raining1123** [comment] 2022-07-18 07:57
+1

**Comment by septs** [comment] 2023-03-25 12:32
Duplicate of https://github.com/Snipaste/feedback/issues/711

**Closed by septs** 2023-03-25 12:32 UTC
