### ISSUE TITLE
识别图中文字的功能到剪贴板；Identify the function of the text in the figure to the clipboard

### ISSUE THREAD

**Issue by luojiwen** [Snipaste/feedback#2318] opened 2022-08-24 05:52 UTC
### 功能描述

1.有时候需要看截图里面的文字，要自己一个一个对着贴图照着敲。想着看看能不能出一个，截图后然后可以圈选识别区域，然后进行文字的识别，然后复制到剪贴板上面，这样就很方便
2.截屏文字翻译功能，截的图里面的字，可以进行文字翻译；

1. Sometimes you need to look at the text in the screenshot and knock one by one against the map. I want to see if I can make one. After the screenshot, I can circle the recognition area, then recognize the text, and then copy it to the clipboard. This is very convenient
2. Screenshot text translation function: the words in the screenshot can be translated

**Comment by chenrylee** [comment] 2022-08-24 05:57
让Snipaste做一个简简单单的截/贴图软件吧，OCR功能请参考: https://github.com/microsoft/PowerToys/pull/19172

**Comment by Geeyun-JY3** [comment] 2022-08-24 06:56
Duplicate of #188

**Closed by Geeyun-JY3** 2022-08-24 06:56 UTC
Labels: duplicate
