### ISSUE TITLE
Hoped that the screenshot function with free shape

### ISSUE THREAD

**Issue by 970844297** [Snipaste/feedback#1999] opened 2021-10-15 16:51 UTC
It is hoped that the screenshot function with free shape can be added, rather than just rectangle. Just like the "area screenshot" function of Xiaomi mobile phone

**Comment by 970844297** [comment] 2021-10-17 14:10
不仅仅是椭圆形等规则形状，希望增加的是不规则的形状，即自己手绘边界

**Comment by Geeyun-JY3** [comment] 2021-10-17 14:34
那应该是：#1265

**Comment by Geeyun-JY3** [comment] 2021-12-03 09:52
最早应该是：#1066

**Comment by Geeyun-JY3** [comment] 2022-07-08 05:13
Duplicate of #1066

**Closed by Geeyun-JY3** 2022-07-08 05:13 UTC
