### ISSUE TITLE
The shortcut keys are too cumbersome to press 'cmd+c' 'cmd+1'

### ISSUE THREAD

**Issue by alkene0005** [Snipaste/feedback#2832] opened 2024-01-11 06:17 UTC
### 功能描述

Why don't just press the letter key?
1: rectangle
2: brush
...
Space: Copy to Clipboard
s: Quick Save 
Hopefully, these shortcuts can be configured directly in the configuration file 🙏

**Comment by Geeyun-JY3** [comment] 2024-01-11 07:52
#106、#664、#1859

**Comment by alkene0005** [comment] 2024-01-11 15:22
![1d91fd73270e06d4d298b4eb3680741f](https://github.com/Snipaste/feedback/assets/61105068/39364291-4442-472a-a5af-507707d9f50b)
还是希望你们考虑下... 这个空格和s保存真的很方便很迅速 我在这款软件中经常使用

**Comment by Geeyun-JY3** [comment] 2024-04-16 05:31
Duplicate of #1859

**Closed by Geeyun-JY3** 2024-04-16 05:31 UTC
Labels: duplicate
