### ISSUE TITLE
The function of extracting text from picture is realized after the screenshot is pasted，like Wechat、QQ

### ISSUE THREAD

**Issue by CHM00** [Snipaste/feedback#2721] opened 2023-09-19 01:17 UTC
### 功能描述

It is very convenient in daily use, when you need to extract the image of the text, symbols to copy the content you want. Because you can't do this, you can't copy, and you waste a lot of time by opening other software or cumbersome manual typing.

**Comment by Geeyun-JY3** [comment] 2023-09-19 03:52
Duplicate of #188

**Closed by Geeyun-JY3** 2023-09-19 03:52 UTC
Labels: duplicate
