### ISSUE TITLE
Serial number with a circular filled background

### ISSUE THREAD

**Issue by sjhsbhqf** [Snipaste/feedback#2479] opened 2023-01-26 13:35 UTC
### Feature Description

As is shown in the graph, When multi-step operations are involved, we need to add a sequence number, but the current text tool does not have the function of filling the background and setting the shape of the filling background as a circle or rectangle.

 If you can add this feature, it will be convenient and beautiful to add serial numbers later

![image](https://user-images.githubusercontent.com/41407099/214848576-666a3766-7a0a-48ad-b4b3-f6f7f92ce719.png)

**Comment by Geeyun-JY3** [comment] 2023-01-26 15:03
Duplicate of https://github.com/Snipaste/feedback/issues/227#issuecomment-628125908

**Closed by Geeyun-JY3** 2023-01-26 15:03 UTC
Labels: duplicate

**Comment by sjhsbhqf** [comment] 2023-01-26 15:05
Thanks I know
