### ISSUE TITLE
Feature request: reverse image search

### ISSUE THREAD

**Issue by nightkall** [Snipaste/feedback#845] opened 2018-03-12 13:21 UTC
A button to search for similar images in [**Google**](https://www.google.es/search?q=snipaste&tbm=isch&tbs=simg:CAQSlwEJ3Hdw0e9PXPIaiwELEKjU2AQaBAgVCAoMCxCwjKcIGmIKYAgDEii_1E7sT7AKVE5gTmxPGHZwTwx2LE7o-1D_1FP9M_1jT3YP8M_1kj28PvY_1GjDrv8qUTm708QmgfOD9pYjklcRg6dq2_1mv6NB9GkBKtNeD2wPTZJpvpcrMNmKCOk70gBAwLEI6u_1ggaCgoICAESBD4z1LYM) and similar reverse image search engines like: [Bing](https://www.bing.com/images/search?q=imgurl:https%3a%2f%2fi.v2ex.co%2f71Ftp04b.png&view=detailv2&selectedIndex=0&pageurl=http%3a%2f%2fwww.squobble.com&mode=ImageViewer&iss=sbi), [Baidu](http://image.baidu.com/n/pc_search?queryImageUrl=https%3A%2F%2Fi.v2ex.co%2F71Ftp04b.png&querySign=&fromPage=upload&errNo=1&errMsgAdd=download_url&uptype=), [Yandex](https://www.yandex.com/images/search?rpt=imageview&img_url=https%3A%2F%2Fi.v2ex.co%2F71Ftp04b.png) or [**TinEye**](https://www.tineye.com/search/54f3b56dfb0147359feb739d80811fa4e3951622/). This is useful to identify what are you seeing, even identify people and objects on screen.

Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by liulex** [comment] 2018-03-23 16:34
Good advise! It may be implemented as a plugin in the future.

**Comment by septs** [comment] 2021-02-16 13:55
Duplicate of #1033

**Closed by septs** 2021-02-16 13:55 UTC
Labels: plugin
