### ISSUE TITLE
About the rectangle and ellipse functions

### ISSUE THREAD

**Issue by brandonzhihui** [Snipaste/feedback#2241] opened 2022-06-14 07:11 UTC
### 功能描述

I want to rotate the rectangle and ellipse to circle the content more precisely

**Comment by Geeyun-JY3** [comment] 2022-06-14 09:39
You need Pro: https://docs.snipaste.com/pro?id=snipaste-2-pro-vs-free-version

**Comment by Geeyun-JY3** [comment] 2022-07-08 06:52
Duplicate of #877

**Closed by Geeyun-JY3** 2022-07-08 06:52 UTC
Labels: duplicate
